---

- name: ansible to provide machines
  hosts: "aws_ec2"
  remote_user: ubuntu
  become: true
  
  tasks:

    - name: Install apt-transport-https
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - lsb-release
          - gnupg
        state: latest
        update_cache: true

    - name: Add signing key
      ansible.builtin.apt_key:
        url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
        state: present

    - name: Add repository into sources list
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ ansible_architecture }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
        state: present
        filename: docker

    - name: Install Docker
      ansible.builtin.apt:
        name:
          - docker
          - docker.io
          - docker-compose
          - docker-registry
        state: latest
        update_cache: true

    - name: Install Ansible and pip
      ansible.builtin.apt:
        name:
          - ansible
          - python3-pip
        state: latest
        update_cache: true
    
    - name: Install python libraries 
      ansible.builtin.pip:
        name:
          - boto3
          - botocore

    - name: Install openjdk 
      ansible.builtin.pip:
        name:
          - openjdk-18-jre

    - name: Creates directory
      file:
        path: /etc/ansible
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: 0775
        recurse: yes

    - name: provide ansible.cfg 
      ansible.builtin.copy:
        src: files/ansible.cfg
        dest: /etc/ansible/ansible.cfg
        owner: root
        group: root
    
    - name: provide ssh key
      ansible.builtin.copy:
        src: files/duvan.ramirezs.keypair.1.pem
        dest: /home/ubuntu/
        owner: root
        group: root
    
    - name: provide ssh Github
      ansible.builtin.copy:
        src: files/id_ed25519
        dest: ~/.ssh/id_ed25519
        owner: root
        group: root
        mode: 600
    
    - name: provide ssh pub Github
      ansible.builtin.copy:
        src: files/id_ed25519.pub
        dest: ~/.ssh/id_ed25519.pub
        owner: root
        group: root

    - name: set ansible.cfg path
      ansible.builtin.lineinfile:
        path: /etc/environment
        line: "ANSIBLE_CONFIG=/etc/ansible/ansible.cfg"
        create: yes
